config/routes.rb
AclManager::Engine.routes.draw do
  root to: 'roles#index'

  resources :roles
  resources :acls do
    get 'build_all', on: :collection
  end
end

app/models/acl_manager/acl.rb
require_dependency "acl_manager/builder"

module AclManager
  class Acl < ActiveRecord::Base
   extend AclManager::Builder

    acts_as_nested_set
    has_and_belongs_to_many :roles, class_name: AclManager::Role.name,
      join_table: 'acl_manager_acls_roles',
      foreign_key: 'acl_manager_acl_id',
      association_foreign_key: 'acl_manager_role_id'

    validates :action, uniqueness: {scope: [:namespace, :controller]}
    validates :name, uniqueness: true

    scope :inner_node, ->(acl){ where('lft <= ?', acl.lft).where('rgt >= ?', acl.rgt) }
    scope :outter_nodes, ->(acl){ where('lft >= ?', acl.lft).where('rgt <= ?', acl.rgt) }

    def self.permit!(acl)
      if(acl.nil?)
        Rails.logger.warn '[AclManager] Acl is nil for permission'
        true
      else
        inner_node(acl).limit(1).any?
      end
    end

    def included? role
      role_ids.include?(role.id)
    end

    class << self
      def root
        find_or_create_by(name: '*')
      end

      def root_and_descendents
        root.self_and_descendants
      end
    end
  end
end

app/models/acl_manager/role.rb
module AclManager
  class Role < ActiveRecord::Base
    has_and_belongs_to_many :acls,
      class_name: AclManager::Acl.name,
      join_table: 'acl_manager_acls_roles',
      foreign_key: 'acl_manager_role_id',
      association_foreign_key: 'acl_manager_acl_id'

    validates :name, presence: true
    validates :name, uniqueness: true

    default_scope { where(active: true) }

    def included? acl
      acl_ids.include?(acl.id)
    end

    def name
      I18n.t("activerecord.attributes.acl_manager.role.#{super}", default: super)
    end
  end
end

app/controllers/acl_manager/acls_controller.rb
require_dependency "acl_manager/application_controller"

module AclManager
  class AclsController < ApplicationController
    before_action :set_acl, only: [:show, :edit, :update, :destroy]

    def index
      @acls = Acl.all
    end

    def show; end

    def new
      @acl = Acl.new
    end

    def edit; end

    def create
      @acl = Acl.new(acl_params)

      if @acl.save
        redirect_to @acl, notice: t('notices.create', model: Acl.model_name.human)
      else
        render :new
      end
    end

    def update
      if @acl.update(acl_params)
        redirect_to @acl, notice: t('notices.update', model: Acl.model_name.human)
      else
        render :edit
      end
    end

    def destroy
      @acl.destroy
      redirect_to acls_url, notice: t('notices.destroy', model: Acl.model_name.human)
    end

    def build_all
      AclManager::Acl.build_all!
      flash[:notice] = t('notices.acl.build_all')
      redirect_to acls_path
    end

    private

    def set_acl
      @acl = Acl.find(params[:id])
    end

    def acl_params
      params.require(:acl).permit(:name, :namespace, :controller, :action, :verb, :helper, :path, :parent_id, :lft, :rgt)
    end
  end
end

app/controllers/acl_manager/application_controller.rb
module AclManager
  class ApplicationController < ActionController::Base
  end
end

app/controllers/acl_manager/roles_controller.rb
require_dependency "acl_manager/application_controller"

module AclManager
  class RolesController < ApplicationController
    before_action :set_role, only: [:show, :edit, :update, :destroy]
    before_action :set_acls, only: [:new, :edit]

    def index
      @roles = Role.unscoped.all
    end

    def show; end

    def new
      @role = Role.new
    end

    def edit; end

    def create
      @role = Role.new(role_params)

      if @role.save
        redirect_to @role, notice: t('notices.create', model: Role.model_name.human)
      else
        render :new
      end
    end

    def update
      if @role.update(role_params)
        redirect_to @role, notice: t('notices.update', model: Role.model_name.human)
      else
        render :edit
      end
    end

    def destroy
      @role.destroy
      redirect_to roles_url, notice: t('notices.destroy', model: Role.model_name.human)
    end

    private

    def set_acls
      @acls = Acl.root_and_descendents
    end

    def set_role
      @role = Role.unscoped.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name, :active, { acl_ids: [] })
    end
  end
end

app/helpers/acl_manager/acls_helper.rb
module AclManager
  module AclsHelper
  	include ActionView::Helpers::UrlHelper

	  def link_to(*args, &block)
	    @last_param = args.last
	    if block_given?
	      options = args.first || {}
	      return default_name(args, capture(&block)) unless permit!(options)
	    else
	      options = args[1] || {}
	      return default_name(args, args.first) unless permit!(options)
	    end

	    super
	  end

	  def permit! options, last_param = nil
	    @options = options
	    @last_param = last_param unless last_param.nil?
	    current_user.nil? || black_listed? || current_user.permit!(find_acl)
	  end

	  private

	  def current_user
	  	User.first
	  end

	  def default_name(args, name)
	    args.last.is_a?(Hash) && args.last[:show_name] ?
	      content_tag(:a, name, args.last.reject { |key, value| key == :show_name }) : ''
	  end

	  def black_listed?
	    @last_param.is_a?(Hash) && @last_param[:no_acl]
	  end

	  def find_acl
	    AclManager::Acl.find_by(find_route)
	  end

	  def find_route
	    method = (@last_param.is_a?(Hash) && !@last_param[:method].nil?) ? @last_param : {}
	    url_path = "#{request.protocol}#{request.host}:#{request.port}#{url_for(@options)}"
	    AclManager::Routing::Recognizer.fullpath(url_path, method)
	  end
  end
end

app/helpers/acl_manager/application_helper.rb
module AclManager
  module ApplicationHelper
    def nested_li(objects, &block)
      objects = objects.order(:lft) if objects.is_a? Class

      return '' if objects.size == 0

      output = '<ul><li>'
      path = [nil]

      objects.each_with_index do |o, i|
        if o.parent_id != path.last
          # We are on a new level, did we descend or ascend?
          if path.include?(o.parent_id)
            # Remove the wrong trailing path elements
            while path.last != o.parent_id
              path.pop
              output << '</li></ul>'
            end
            output << '</li><li>'
          else
            path << o.parent_id
            output << '<ul><li>'
          end
        elsif i != 0
          output << '</li><li>'
        end
        output << capture(o, path.size - 1, &block)
      end

      output << '</li></ul>' * path.length
      output.html_safe
    end
  end
end

app/views/acl_manager/acls/_form.html.erb
<%= form_for(@acl) do |f| %>
  <% if @acl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acl.errors.count, "error") %> prohibited this acl from being saved:</h2>

      <ul>
      <% @acl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :namespace %><br>
    <%= f.text_field :namespace %>
  </div>
  <div class="field">
    <%= f.label :controller %><br>
    <%= f.text_field :controller %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :verb %><br>
    <%= f.text_field :verb %>
  </div>
  <div class="field">
    <%= f.label :helper %><br>
    <%= f.text_field :helper %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :lft %><br>
    <%= f.number_field :lft %>
  </div>
  <div class="field">
    <%= f.label :rgt %><br>
    <%= f.number_field :rgt %>
  </div>
  <div class="actions">
    <%= f.submit t('commands.save', model: @acl.model_name.human) %>
  </div>
<% end %>

app/views/acl_manager/acls/edit.html.erb
<h1>Editing Acl</h1>

<%= render 'form' %>

<%= link_to 'Show', @acl %> |
<%= link_to 'Back', acls_path %>

app/views/acl_manager/acls/index.html.erb
<div class="posts">
  <h1 class="content-subhead">
    <%= AclManager::Acl.model_name.human(count: :other) %> ::
    <%= link_to t('commands.new_model', model: AclManager::Acl.model_name.human), new_acl_path %> ::
    <%= link_to t('.build_all'), build_all_acls_path %>
  </h1>

  <table class="pure-table pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>id</th>
        <th>parent_id</th>
        <th>namespace</th>
        <th>name</th>
        <th>path</th>
        <th>helper</th>
      </tr>
    </thead>
    <tbody>
      <% @acls.each do |acl| %>
        <tr>
          <td><%= acl.id %></td>
          <td><%= acl.parent_id %></td>
          <td><%= acl.namespace %></td>
          <td><%= acl.name %></td>
          <td><%= acl.verb %> <%= acl.path %></td>
          <td><%= acl.helper %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/acl_manager/acls/new.html.erb
<h1><%= t('commands.new_model', model: @acl.model_name.human) %></h1>

<%= render 'form' %>

<%= link_to t('commands.cancel'), acls_path %>

app/views/acl_manager/acls/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @acl.name %>
</p>

<p>
  <strong>Namespace:</strong>
  <%= @acl.namespace %>
</p>

<p>
  <strong>Controller:</strong>
  <%= @acl.controller %>
</p>

<p>
  <strong>Action:</strong>
  <%= @acl.action %>
</p>

<p>
  <strong>Verb:</strong>
  <%= @acl.verb %>
</p>

<p>
  <strong>Helper:</strong>
  <%= @acl.helper %>
</p>

<p>
  <strong>Path:</strong>
  <%= @acl.path %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @acl.parent_id %>
</p>

<p>
  <strong>Lft:</strong>
  <%= @acl.lft %>
</p>

<p>
  <strong>Rgt:</strong>
  <%= @acl.rgt %>
</p>

<%= link_to 'Edit', edit_acl_path(@acl) %> |
<%= link_to 'Back', acls_path %>

app/views/acl_manager/roles/_form.html.erb
<%= form_for @role, :html => { :class => "pure-form pure-form-aligned" } do |f| %>
  <fieldset>
    <div class="pure-control-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
    </div>
    <div class="pure-control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, cols: 60 %>
    </div>
    <div class="pure-controls">
      <%= f.label :active, class: 'pure-checkbox' do %>
        <%= f.check_box :active %>
        Active
      <% end %>
    </div>

    <h3 class="panel-title">Permissions</h3>

    <div id="acl-tree">
      <%= nested_li(@acls) do |acl| %>
        <label class="pure-checkbox">
          <%= check_box_tag('role[acl_ids][]', acl.id, @role.included?(acl)) %>
          <%= acl.name %>
        </label>
      <% end %>
    </div>

    <%= f.submit t('commands.save', model: @role.model_name.human), class: 'pure-button pure-button-primary' %>
    <%= link_to t('commands.cancel'), roles_path, class: 'button-error pure-button' %>
  </fieldset>
<% end %>

app/views/acl_manager/roles/edit.html.erb
<div class="posts">
  <h1 class="content-subhead"><%= @role.name %></h1>

  <h2>Editing Role</h2>

  <%= render 'form' %>

  <%= link_to t('commands.show'), @role %> |
  <%= link_to t('commands.back'), roles_path %>
</div>

app/views/acl_manager/roles/index.html.erb
<div class="posts">
<h1 class="content-subhead"><%= AclManager::Role.model_name.human(count: :other) %></h1>

<% @roles.each do |role| %>
  <section class="post">
    <header class="post-header">
      <%= image_tag "acl_manager/#{role.active}.png", class: 'post-avatar', height: '48', width: '48' %>

      <h2 class="post-title"><%= role.name %></h2>
      <p class="post-meta">
        <%= link_to t('commands.edit_model', model: role.model_name.human), acl_manager.edit_role_path(role) %> :: <%= t('.active') %> <a class="post-category <%= role.active %>" href="#"><%= role.active? %></a>
      </p>
    </header>

    <div class="post-description">
      <p><%= role.description %></p>
    </div>
  </section>
<% end %>
</div>
<%= link_to t('commands.new_model', model: AclManager::Role.model_name.human), acl_manager.new_role_path, class: 'pure-button' %>

app/views/acl_manager/roles/new.html.erb
<h1><%= t('commands.new_model', model: @role.model_name.human) %></h1>

<%= render 'form' %>

<%= link_to t('commands.back'), roles_path %>

app/views/acl_manager/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @role.active %>
</p>

<%= link_to t('commands.edit'), edit_role_path(@role) %> |
<%= link_to t('commands.back'), roles_path %>

app/views/layouts/acl_manager/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AclManager</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A layout example that shows off a blog page with a list of posts.">


  <%= stylesheet_link_tag "acl_manager/application", media: "all" %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

  <!--[if lte IE 8]>
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
  <!--<![endif]-->


  <%= javascript_include_tag "acl_manager/application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
      <div class="header">
        <h1 class="brand-title">Acl Manager</h1>
        <h2 class="brand-tagline">Access Control Level by Flexa IT</h2>

        <nav class="nav">
          <ul class="nav-list">
            <li class="nav-item">
              <%= link_to AclManager::Role.model_name.human(count: :other), acl_manager.roles_path, class: 'pure-button' %>
            </li>
            <li class="nav-item">
              <%= link_to AclManager::Acl.model_name.human(count: :other), acl_manager.acls_path, class: 'pure-button' %>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
      <p id="notice"><%= notice %></p>
      <div>
        <%= yield %>
        <div class="footer">
          <div class="pure-menu pure-menu-horizontal">
            <ul>
              <li class="pure-menu-item"><a href="http://purecss.io/" class="pure-menu-link">About</a></li>
              <li class="pure-menu-item"><a href="http://twitter.com/yuilibrary/" class="pure-menu-link">Twitter</a></li>
              <li class="pure-menu-item"><a href="http://github.com/yahoo/pure/" class="pure-menu-link">GitHub</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>